development:
  adapter: mysql2
  database: railsapp
  host: 127.0.0.1
  encoding: utf8
  port: 3306
  username: root
  password:

test:
  adapter: mysql2
  database: railsapp_test
  host: 127.0.0.1
  encoding: utf8
  port: 3306
  username: root
  password:
